export enum SignupFlowStatus {
  SENTINEL_ONE_SIGNIN = 'SENTINEL_ONE_SIGNIN',
  SENTINEL_ONE_SSO = 'SENTINEL_ONE_SSO',
  SENTINEL_ONE_SSO_PENDING = 'SENTINEL_ONE_SSO_PENDING',
  SENTINEL_ONE_SSO_RESEND = 'SENTINEL_ONE_SSO_RESEND',
  PORTAL_SIGNUP = 'PORTAL_SIGNUP',
  ALL_DONE = 'ALL_DONE',
  USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED',
}
