import { SearchFilter } from '@/src/enums/search-filter'

export const AlertsColumn = [
  {
    Header: 'アラートID',
    accessor: 'id',
    onlyCsv: false,
    searchable: true,
    type: 'text',
    allowedOptions: [SearchFilter.EQUALS],
  },
  {
    Header: '脅威名',
    accessor: 'threatInfo.threatName',
    onlyCsv: false,
    searchable: true,
    type: 'text',
    allowedOptions: [SearchFilter.CONTAINS],
  },
  {
    Header: 'ステータス',
    accessor: 'threatInfo.incidentStatusDescription',
    onlyCsv: false,
    searchable: true,
    type: 'boolean',
    allowedOptions: [SearchFilter.EQUALS],
  },
  {
    Header: '緩和ステータス',
    accessor: 'threatInfo.mitigationStatusDescription',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: '分類',
    accessor: 'threatInfo.classification',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: 'エンジン',
    accessor: 'threatInfo.engines',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: 'イニシエート',
    accessor: 'threatInfo.initiatedByDescription',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: 'OS',
    accessor: 'agentDetectionInfo.agentOsName',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: 'OSバージョン',
    accessor: 'agentDetectionInfo.agentOsRevision',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
  {
    Header: '発生日',
    accessor: 'threatInfo.identifiedAt',
    onlyCsv: false,
    searchable: false,
    type: 'text',
    allowedOptions: [
      SearchFilter.EQUALS,
      SearchFilter.NOT_EQUALS,
      SearchFilter.STARTS_WITH,
      SearchFilter.ENDS_WITH,
      SearchFilter.CONTAINS,
    ],
  },
]
